"""Generate a lightweight client-side search index (label + href only) from the
destination and package data, so the homepage hero search can resolve queries
without bundling the full data files. Re-run after adding destinations/packages."""
import re, io, json

dtext = open("src/data/destinations.ts", encoding="utf-8").read()
cs = dtext.find("comingSoonDestinations")
live_text = dtext[:cs] if cs > 0 else dtext
dests = re.findall(
    r'name:\s*"([^"]+)",\s*slug:\s*"([^"]+)",\s*region:\s*"([^"]+)"', live_text, re.S
)

ptext = open("src/data/packages.ts", encoding="utf-8").read()
# Iterate package blocks so we can read each package's category and skip the
# archived "educational" ones (hidden from the live site per client request).
pkgs = []
for block in re.split(r"\n  \{\n", ptext):
    m = re.search(
        r'title:\s*"([^"]+)",\s*slug:\s*"([^"]+)",\s*destinationName:\s*"([^"]+)",\s*destinationSlug:',
        block, re.S,
    )
    if not m:
        continue
    cat = re.search(r'category:\s*"([^"]+)"', block)
    if cat and cat.group(1) == "educational":
        continue
    pkgs.append(m.groups())

entries = []
for name, slug, region in dests:
    entries.append({"label": name, "href": f"/destinations/{slug}", "type": "Destination", "sub": region})
for title, slug, dn in pkgs:
    entries.append({"label": title, "href": f"/packages/{slug}", "type": "Package", "sub": dn})

lines = [
    "// AUTO-GENERATED by scripts/gen_search_index.py - do not edit by hand.",
    "// Lightweight search index for the homepage hero search (label + href only).",
    'export interface SearchEntry {',
    "  label: string",
    "  href: string",
    '  type: "Destination" | "Package"',
    "  sub: string",
    "}",
    "",
    "export const searchIndex: SearchEntry[] = [",
]
for e in entries:
    lines.append("  " + json.dumps(e, ensure_ascii=False) + ",")
lines.append("]")
with io.open("src/data/searchIndex.ts", "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"Wrote {len(entries)} entries ({len(dests)} destinations + {len(pkgs)} packages)")
