/**
 * packageTags.ts - activity + vibe taxonomy per package, for the faceted
 * "explore" browse on /packages, /destinations and /categories.
 *
 * AUTO-GENERATED by keyword inference (category + destination + title), then
 * hand-reviewable. Each package slug maps to its activity types and vibes.
 * Edit freely to correct any mis-tags.
 */
export type PackageTags = { activities: string[]; vibes: string[] }

export const packageTags: Record<string, PackageTags> = {
  "ladakh-complete-circuit": {
    "activities": [
      "Snow & Winter",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "kerala-backwaters-spices": {
    "activities": [
      "Backwaters"
    ],
    "vibes": [
      "Backwaters & Lakes"
    ]
  },
  "goa-beach-heritage": {
    "activities": [
      "Beach",
      "Heritage & Culture"
    ],
    "vibes": [
      "Beaches",
      "Heritage Cities"
    ]
  },
  "bali-island-of-gods": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Islands"
    ]
  },
  "char-dham-yatra-helicopter": {
    "activities": [
      "Pilgrimage"
    ],
    "vibes": [
      "Hills & Mountains",
      "Spiritual"
    ]
  },
  "bali-nusa-islands-explorer": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Islands"
    ]
  },
  "leh-to-leh-bike-suv": {
    "activities": [
      "Snow & Winter",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "leh-to-leh-with-turtuk": {
    "activities": [
      "Snow & Winter",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "manali-leh-manali-circuit": {
    "activities": [
      "Hill Station",
      "Snow & Winter",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "manali-leh-srinagar": {
    "activities": [
      "Hill Station",
      "Snow & Winter",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "srinagar-leh-manali": {
    "activities": [
      "Hill Station",
      "Snow & Winter",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "5-nights-with-dambulla": {
    "activities": [
      "Wildlife Safari",
      "Lakes & Nature"
    ],
    "vibes": [
      "Islands",
      "Backwaters & Lakes"
    ]
  },
  "andaman-6-days-package": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Islands"
    ]
  },
  "andaman-8-days": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Islands"
    ]
  },
  "azerbaijan-package-highlights": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "badami-hampi-chikmangluru": {
    "activities": [
      "Hill Station",
      "Heritage & Culture",
      "Road Trip"
    ],
    "vibes": [
      "Heritage Cities"
    ]
  },
  "coorg-wayand": {
    "activities": [
      "Wildlife Safari",
      "Backwaters",
      "Hill Station",
      "Heritage & Culture"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes",
      "Heritage Cities"
    ]
  },
  "dudhsagar-waterfall-trek": {
    "activities": [
      "Trek",
      "Beach",
      "Adventure Sports"
    ],
    "vibes": [
      "Beaches",
      "Hills & Mountains"
    ]
  },
  "saurashtra-heritage": {
    "activities": [
      "Wildlife Safari",
      "Pilgrimage",
      "Heritage & Culture"
    ],
    "vibes": [
      "Heritage Cities"
    ]
  },
  "kerala-7-days": {
    "activities": [
      "Backwaters",
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "rann-of-kutch": {
    "activities": [
      "Heritage & Culture",
      "Desert"
    ],
    "vibes": [
      "Desert",
      "Heritage Cities"
    ]
  },
  "scenic-sri-lanka": {
    "activities": [
      "Wildlife Safari"
    ],
    "vibes": [
      "Islands"
    ]
  },
  "scintillating-tropical-tour-to-sri-lanka": {
    "activities": [
      "Lakes & Nature"
    ],
    "vibes": [
      "Islands",
      "Backwaters & Lakes"
    ]
  },
  "seven-sisters": {
    "activities": [
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "tadoba": {
    "activities": [
      "Wildlife Safari"
    ],
    "vibes": []
  },
  "kashmir-essence-srinagar-pahalgam": {
    "activities": [
      "Hill Station",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "kashmir-grand-jammu-srinagar": {
    "activities": [
      "Hill Station",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "kashmir-offbeat-gurez-sinthan": {
    "activities": [
      "Hill Station",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "himachal-classic-shimla-manali": {
    "activities": [
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "himachal-grand-circuit": {
    "activities": [
      "Hill Station",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "spiti-valley-adventure": {
    "activities": [
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "rajasthan-lakes-and-hills": {
    "activities": [
      "Hill Station",
      "Heritage & Culture",
      "Lakes & Nature"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes",
      "Heritage Cities"
    ]
  },
  "char-dham-by-road": {
    "activities": [
      "Pilgrimage"
    ],
    "vibes": [
      "Hills & Mountains",
      "Spiritual"
    ]
  },
  "uttarakhand-hills-and-pilgrimage": {
    "activities": [
      "Wildlife Safari",
      "Pilgrimage",
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains",
      "Spiritual"
    ]
  },
  "mussoorie-and-garhwal-hills": {
    "activities": [
      "Hill Station",
      "Lakes & Nature"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "central-mp-wilderness": {
    "activities": [
      "Wildlife Safari"
    ],
    "vibes": []
  },
  "mp-tiger-and-hills": {
    "activities": [
      "Wildlife Safari",
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "statue-of-unity-narmada": {
    "activities": [
      "Heritage & Culture"
    ],
    "vibes": [
      "Hills & Mountains",
      "Heritage Cities"
    ]
  },
  "mahabaleshwar-lonavala-weekend": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "matheran-weekend": {
    "activities": [
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "igatpuri-vineyard-sandhan-valley": {
    "activities": [
      "Trek"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "konkan-coastal": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "pelling-gangtok-ravangla": {
    "activities": [
      "Hill Station",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "lamahatta-tinchuley-chatakpur-darjeeling": {
    "activities": [
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "darjeeling-gangtok-classic": {
    "activities": [
      "Hill Station",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "dooars-buxa-jaldapara-gorumara": {
    "activities": [
      "Wildlife Safari",
      "Road Trip"
    ],
    "vibes": []
  },
  "hyderabad-city-break-4n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "meghalaya-essence": {
    "activities": [
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "north-sikkim-lachen-lachung": {
    "activities": [
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "sikkim-family-circuit": {
    "activities": [
      "Hill Station",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "bastar-chitrakote": {
    "activities": [
      "Adventure Sports"
    ],
    "vibes": []
  },
  "chhattisgarh-wildlife-heritage": {
    "activities": [
      "Wildlife Safari",
      "Heritage & Culture"
    ],
    "vibes": [
      "Heritage Cities"
    ]
  },
  "arunachal-tawang-classic": {
    "activities": [
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "arunachal-tawang-in-depth": {
    "activities": [
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "arunachal-tawang-kaziranga": {
    "activities": [
      "Wildlife Safari",
      "Hill Station",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "assam-kaziranga-jorhat-dibrugarh": {
    "activities": [
      "Wildlife Safari"
    ],
    "vibes": []
  },
  "assam-manas-nameri-kaziranga": {
    "activities": [
      "Wildlife Safari"
    ],
    "vibes": []
  },
  "karnataka-mysore-coorg": {
    "activities": [
      "Hill Station",
      "Heritage & Culture"
    ],
    "vibes": [
      "Hills & Mountains",
      "Heritage Cities"
    ]
  },
  "kerala-munnar-thekkady-alleppey": {
    "activities": [
      "Backwaters",
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "kerala-cochin-munnar-thekkady": {
    "activities": [
      "Backwaters",
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "karnataka-kerala-coorg-wayanad": {
    "activities": [
      "Backwaters",
      "Hill Station",
      "Heritage & Culture"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes",
      "Heritage Cities"
    ]
  },
  "karnataka-coorg-ooty": {
    "activities": [
      "Hill Station",
      "Heritage & Culture"
    ],
    "vibes": [
      "Hills & Mountains",
      "Heritage Cities"
    ]
  },
  "mysore-ooty-kodaikanal": {
    "activities": [
      "Hill Station",
      "Heritage & Culture"
    ],
    "vibes": [
      "Hills & Mountains",
      "Heritage Cities"
    ]
  },
  "kerala-munnar-alleppey-kovalam": {
    "activities": [
      "Backwaters",
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "kerala-ultimate-escape": {
    "activities": [
      "Backwaters",
      "Hill Station"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "lakshadweep-coral-islands": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Islands"
    ]
  },
  "karnataka-udupi-murudeshwar-gokarna": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "vietnam-classic-6n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "vietnam-phu-quoc-4n": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Beaches"
    ]
  },
  "vietnam-full-circuit-9n": {
    "activities": [
      "Road Trip"
    ],
    "vibes": []
  },
  "vietnam-grand-14n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "thailand-bangkok-pattaya-4n": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Beaches"
    ]
  },
  "thailand-grand-beach-8n": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Islands",
      "Beaches"
    ]
  },
  "thailand-bangkok-samui-phuket-6n": {
    "activities": [
      "Beach"
    ],
    "vibes": [
      "Islands"
    ]
  },
  "hong-kong-essentials-4n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "hong-kong-macau-6n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "dubai-classic-6n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "dubai-abu-dhabi-8n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "singapore-classic-4n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "singapore-bintan-6n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "singapore-malaysia-6n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "singapore-cruise-malaysia-8n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "malaysia-kl-penang-langkawi-7n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "philippines-grand-circuit-9d": {
    "activities": [
      "Road Trip"
    ],
    "vibes": []
  },
  "bhutan-discovery-7n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "bhutan-cultural-10n": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "bhutan-grand-12n": {
    "activities": [
      "Leisure"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "south-africa-highlights-10d": {
    "activities": [
      "Wildlife Safari"
    ],
    "vibes": []
  },
  "kenya-safari-7d": {
    "activities": [
      "Wildlife Safari",
      "Lakes & Nature"
    ],
    "vibes": [
      "Backwaters & Lakes"
    ]
  },
  "jordan-highlights-6d": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "iceland-northern-lights-7d": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "finland-lapland-northern-lights-7d": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "western-europe-grand-tour-11d": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "eastern-europe-prague-vienna-budapest-8d": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "australia-highlights-9d": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "new-zealand-explorer-10d": {
    "activities": [
      "Leisure"
    ],
    "vibes": [
      "Islands"
    ]
  },
  "kazakhstan-almaty-5d": {
    "activities": [
      "Lakes & Nature"
    ],
    "vibes": [
      "Backwaters & Lakes"
    ]
  },
  "uzbekistan-silk-road-8d": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "japan-golden-route": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "japan-grand-tour": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "japan-gourmet-trail": {
    "activities": [
      "Leisure"
    ],
    "vibes": []
  },
  "zanskar-river-rafting-expedition": {
    "activities": [
      "River Rafting",
      "Snow & Winter",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "brahmaputra-river-rafting-expedition": {
    "activities": [
      "River Rafting",
      "Road Trip"
    ],
    "vibes": []
  },
  "subansiri-river-rafting-expedition": {
    "activities": [
      "River Rafting",
      "Road Trip"
    ],
    "vibes": []
  },
  "kali-sarda-river-rafting": {
    "activities": [
      "River Rafting"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "upper-alaknanda-river-rafting": {
    "activities": [
      "River Rafting"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "tons-thriller-rafting-expedition": {
    "activities": [
      "River Rafting",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "total-tons-river-rafting": {
    "activities": [
      "River Rafting"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "lower-tons-river-rafting": {
    "activities": [
      "River Rafting"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "har-ki-dun-valley-trek": {
    "activities": [
      "Trek"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "kuari-pass-trek": {
    "activities": [
      "Trek"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "pangarchulla-peak-climb": {
    "activities": [
      "Adventure"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "dodital-lake-trek": {
    "activities": [
      "Trek",
      "Lakes & Nature"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "bali-pass-trek": {
    "activities": [
      "Trek",
      "Beach"
    ],
    "vibes": [
      "Islands",
      "Hills & Mountains"
    ]
  },
  "ruinsara-lake-trek": {
    "activities": [
      "Trek",
      "Lakes & Nature"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "baraadsar-lake-trek": {
    "activities": [
      "Trek",
      "Lakes & Nature"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "dayara-bugyal-trek": {
    "activities": [
      "Trek"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "audens-col-expedition-trek": {
    "activities": [
      "Trek",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "kirti-glacier-gangotri-trek": {
    "activities": [
      "Trek"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "bandarpunch-climb-expedition": {
    "activities": [
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "traills-pass-expedition-trek": {
    "activities": [
      "Trek",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "panpatia-col-expedition-trek": {
    "activities": [
      "Trek",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains"
    ]
  },
  "markha-valley-trek": {
    "activities": [
      "Trek",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "markha-valley-winter-trek": {
    "activities": [
      "Trek",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "chadar-frozen-zanskar-trek": {
    "activities": [
      "Trek",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "sham-valley-trek": {
    "activities": [
      "Trek",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "sham-valley-winter-trek": {
    "activities": [
      "Trek",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "kang-yatse-ii-climb-expedition": {
    "activities": [
      "Snow & Winter",
      "Road Trip"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "parang-la-trek": {
    "activities": [
      "Trek",
      "Snow & Winter"
    ],
    "vibes": [
      "Hills & Mountains",
      "Snow"
    ]
  },
  "dagala-thousand-lakes-trek": {
    "activities": [
      "Trek",
      "Lakes & Nature"
    ],
    "vibes": [
      "Hills & Mountains",
      "Backwaters & Lakes"
    ]
  },
  "mount-elbrus-climb": {
    "activities": [
      "Adventure"
    ],
    "vibes": []
  }
}
